services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    networks:
      - cc-network
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: abcd
      MINIO_ROOT_PASSWORD: abcdadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "--console-address", ":9001", "/data"]
    volumes:
      - minio_data:/data
    networks:
      - cc-network
    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    depends_on:
      - minio
    image: minio/mc
    networks:
      - cc-network
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 abcd abcdadmin;
      /usr/bin/mc mb  --ignore-existing myminio/default;
      /usr/bin/mc policy set public myminio/default;
      exit 0;
      "

networks:
  cc-network:

volumes:
  minio_data:
  postgres_data:
